movie_match/urls.py
from django.urls import path
from . import views as movie_match_views  # Views from the current app
from movies_project import views as main_views  # Views from the main project

app_name = 'movie_match'

urlpatterns = [
    path('', movie_match_views.index, name='index'),
    path('save_movie_data/<int:movie_id>/', movie_match_views.save_movie_data, name='save_movie_data'),
    path('wheel/', movie_match_views.wheel_of_movies, name='wheel_of_movies'),
    path('plinko/', movie_match_views.plinko, name='plinko'),
    path('login/', main_views.login_view, name='login'),
    path('movie_profile/<int:movie_id>/', movie_match_views.movie_profile, name='movie_profile'),
    path('user_movies/', movie_match_views.user_movies, name='user_movies'),
]

movies_project/urls.py
from django.contrib import admin
from django.urls import path, include  # Import 'include'
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('user_search/', views.user_search, name='user_search'),
    path('add_friend/<int:user_id>/', views.add_friend, name='add_friend'),
    path('admin/', admin.site.urls),
    path('movie_match/', include('movie_match.urls', namespace='movie_match')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

movie_match/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

# Create your models here.

class Movie(models.Model):
    adult = models.BooleanField(default=False)
    backdrop_path = models.CharField(max_length=255, null=True, blank=True)
    genre_ids = models.TextField()
    movie_id = models.IntegerField(unique=True)  # Corresponds to "id" in the JSON
    original_language = models.CharField(max_length=10)
    original_title = models.CharField(max_length=255)
    overview = models.TextField()
    popularity = models.FloatField()
    poster_path = models.CharField(max_length=255, null=True, blank=True)
    release_date = models.DateField()
    title = models.CharField(max_length=255)
    video = models.BooleanField(default=False)
    vote_average = models.FloatField(default=0.0)
    vote_count = models.IntegerField(default=0.0)

    def __str__(self):
        return self.title


class User(AbstractUser):
    friends = models.ManyToManyField('self', related_name='friend_set', symmetrical=True, blank=True)

    movies_interested = models.ManyToManyField('Movie', related_name='interested_users', blank=True)
    movies_not_interested = models.ManyToManyField('Movie', related_name='not_interested_users', blank=True)
    movies_liked = models.ManyToManyField('Movie', related_name='liked_by_users', blank=True)
    movies_disliked = models.ManyToManyField('Movie', related_name='disliked_by_users', blank=True)
    movies_neutral = models.ManyToManyField('Movie', related_name='neutral_users', blank=True)

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="custom_user_groups",
        related_query_name="user",
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="custom_user_permissions",
        related_query_name="user",
    )

    def __str__(self):
        return self.username

movie_match/views.py
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotAllowed, HttpResponseServerError
from .models import *
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core import serializers
import traceback


# Create your views here.

@csrf_exempt
def save_movie_data(request, movie_id=None):
    try:
        if request.method != 'POST':
            return JsonResponse({"error": "Only POST requests are allowed"}, status=405)

        data = json.loads(request.body)
        is_interested = data.get('isInterested')
        is_not_interested = data.get('isNotInterested')
        seen_liked = data.get('seenLiked')
        seen_disliked = data.get('seenDisliked')


        movie, created = Movie.objects.get_or_create(
            movie_id=movie_id,
            defaults={
                'adult': data.get('adult', False),
                'backdrop_path': data.get('backdrop_path'),
                'genre_ids': json.dumps(data.get('genre_ids', [])),
                'original_language': data.get('original_language'),
                'original_title': data.get('original_title'),
                'overview': data.get('overview'),
                'popularity': data.get('popularity'),
                'poster_path': data.get('poster_path'),
                'release_date': data.get('release_date'),
                'title': data.get('title'),
                'video': data.get('video', False),
                'vote_average': data.get('vote_average'),
                'vote_count': data.get('vote_count'),
            }
        )

        if request.user.is_authenticated:
            request.user.movies_interested.remove(movie)
            request.user.movies_not_interested.remove(movie)
            request.user.movies_liked.remove(movie)
            request.user.movies_disliked.remove(movie)
            request.user.movies_neutral.remove(movie)

            if is_interested:
                request.user.movies_interested.add(movie)
            elif is_not_interested:
                request.user.movies_not_interested.add(movie)
            elif seen_liked:
                request.user.movies_liked.add(movie)
            elif seen_disliked:
                request.user.movies_disliked.add(movie)

        interested_movies_qs = request.user.movies_interested.all()[:8]
        interested_movies = serializers.serialize('json', interested_movies_qs)
        return JsonResponse({"message": "Movie data and preferences saved successfully.", "updated_movies": interested_movies}, status=201)


    except Exception as e:
        traceback.print_exc()
        return JsonResponse({"error": f"An error occurred: {e}"}, status=500)

@login_required
def wheel_of_movies(request):
    user = request.user
    interested_movies_qs = user.movies_interested.all()[:8]
    interested_movies = serializers.serialize('json', interested_movies_qs)
    return render(request, "movie_match/wheel_of_movies.html", {
        "interested_movies_json": interested_movies
    })

@login_required
def plinko(request):
    user = request.user
    interested_movies_qs = user.movies_interested.all()[:5]
    interested_movies_length = len(interested_movies_qs) 
    interested_movies = serializers.serialize('json', interested_movies_qs)
    return render(request, "movie_match/plinko.html", {
        'interested_movies_json': interested_movies,
        'interested_movies_length': interested_movies_length,
    })

def index(request):
    return render(request, "home/index.html")

def movie_profile(request, movie_id):
    return render(request, 'movie_match/movie_profile.html', {'movie_id': movie_id})


@login_required
def user_movies(request):
    user = request.user
    user_movies = user.movies_interested.all() | user.movies_not_interested.all() | user.movies_liked.all() | user.movies_disliked.all() | user.movies_neutral.all()
    user_movies_json = serializers.serialize('json', user_movies)
    return JsonResponse(user_movies_json, safe=False)

movie_match/templates/home/Layout_v2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- Title -->
	<title>Movie Matcher</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, minimal-ui, viewport-fit=cover">

	<!-- Favicons Icon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'movie_match/assets/images/favicon.png">
    
    <!-- Global CSS -->
	<link href="{% static 'movie_match/assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'movie_match/assets/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css' %}">
	<link rel="stylesheet" href="{% static 'movie_match/assets/vendor/swiper/swiper-bundle.min.css' %}">
    
	<!-- Stylesheets -->
    <link rel="stylesheet" class="main-css" type="text/css" href="{% static 'movie_match/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" class="main-css" type="text/css" href="{% static 'movie_match/assets/css/style.css' %}">
	
    <!-- Google Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,200;6..12,300;6..12,400;6..12,500;6..12,600;6..12,700;6..12,800;6..12,900;6..12,1000&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    
    <!-- React -->
    <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
</head>   
<body class="overflow-hidden header-large">
<div class="page-wrapper">
    
	<!-- Preloader -->
	<div id="preloader">
		<div class="loader">
			<div class="load-circle"><div></div><div></div></div>
		</div>
	</div>
    <!-- Preloader end-->
	
	<!-- Header -->
		<header class="header header-fixed border-0">
			<div class="container">
				<div class="header-content">
					<div class="left-content">
						<a href="javascript:void(0);" class="menu-toggler">
							<i class="fa-solid fa-bars"></i>
						</a>
					</div>
					<div class="mid-content header-logo">
						<a href="{% url 'index' %}">
							<img src="{% static 'movie_match/assets/images/MovieMatcher.png' %}" alt="">
						</a>
					</div>
					
					<div class="right-content d-flex gap-2">
						<a href="javascript:void(0);" class="filter-icon icon-fill" data-bs-toggle="offcanvas" data-bs-target="#settingCanvas" aria-controls="offcanvasBottom">
							<i class="fa-solid fa-filter"></i>
						</a>
					</div>
				</div>
			</div>
		</header>
	<!-- Header -->
	
	<!-- Sidebar -->
    <div class="dark-overlay"></div>
	<div class="sidebar">
		<div class="inner-sidebar">
			<a href="profile.html" class="author-box">
				<div class="dz-media">
					<img src="{% static 'movie_match/assets/images/user/pic1.jpg' %}" alt="author-image">
				</div>
				<div class="dz-info">
					<h5 class="name">{{ user.username }}</h5>
					<span>{{ user.email }}</span>
				</div>
			</a>
			<ul class="nav navbar-nav">	
				<li>
					<a class="nav-link active" href="{% url 'index' %}">
						<span class="dz-icon">
							<i class="fa-solid fa-house"></i>
						</span>
						<span>Home</span>
					</a>
				</li>
				<li>
					<a class="nav-link" href="{% url 'movie_match:wheel_of_movies' %}">
						<span class="dz-icon">
							<i class="fa-solid fa-dharmachakra"></i>
						</span>
						<span>Wheel of Movies</span>
					</a>
				</li>
				<li>
					<a class="nav-link" href="{% url 'movie_match:plinko' %}">
						<span class="dz-icon">
							<i class="fa-solid fa-circle"></i>
						</span>
						<span>Plinko</span>
					</a>
				</li>
				<li>
					{% if user.is_authenticated %}
					<a class="nav-link" href="{% url 'profile' user.username %}">
						<span class="dz-icon">
							<i class="fa-solid fa-user"></i>
						</span>
						<span>Profile</span>
					</a>
					{% else %}
					{% endif %}
				</li>
				<li>
					<a class="nav-link" href="{% url 'logout' %}">
						<span class="dz-icon">
							<i class="fa-solid fa-sign-out"></i>
						</span>
						<span>Logout</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
    <!-- Sidebar End -->
	
	<!-- Page Content Start -->
    {% block content %}
    <!-- Content will be overridden by child templates -->
    {% endblock content %}
	<!-- Page Content End -->
	
	<!-- Menubar -->
	<div class="menubar-area style-3 footer-fixed">
		<div class="toolbar-inner menubar-nav">
			<a href="{% url 'index' %}" class="nav-link">
				<i class="fa-solid fa-house"></i>
			</a>
			<a href="{% url 'movie_match:wheel_of_movies' %}" class="nav-link">
				<i class="fa-solid fa-dharmachakra"></i>
			</a>
			<a href="{% url 'movie_match:plinko' %}" class="nav-link">
				<i class="fa-solid fa-circle"></i>
			</a>
			{% if user.is_authenticated %}
			<a href="{% url 'profile' user.username %}" class="nav-link">
				<i class="fa-solid fa-user"></i>
			</a>
			{% else %}
			{% endif %}
		</div>
	</div>
	<!-- Menubar -->
</div>  
<!--**********************************
    Scripts
***********************************-->
<script src="{% static 'movie_match/assets/js/jquery.js' %}"></script>
<script src="{% static 'movie_match/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'movie_match/assets/vendor/swiper/swiper-bundle.min.js' %}"></script><!-- Swiper -->
<script src="{% static 'movie_match/assets/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' %}"></script><!-- Swiper -->
<script src="{% static 'movie_match/assets/js/dz.carousel.js' %}"></script>
<script src="{% static 'movie_match/assets/js/custom.js' %}"></script>
</body>
</html>

movie_match/templates/home/profile.html
{% extends 'home/layout_v2.html' %} <!-- Replace with your base template -->

{% block content %}
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.body.classList.remove("overflow-hidden");
});
</script>
	<!-- Page Content Start -->
	<div class="page-content p-t100 p-b50">
		<div class="container">
			<!-- Nav tabs -->
			<div class="default-tab style-2">
				<div class="tab-content">
					<div class="tab-pane fade active show" id="profile1" role="tabpanel">
						<div class="title-bar">
							<h6 class="title">Interested Movies</h6>
						</div>
						<div class="swiper-btn-center-lr">
							<div class="swiper spot-swiper1 mb-3">            
								<div class="swiper-wrapper">
                  {% for movie in user.movies_interested.all %}
									<div class="swiper-slide">
										<div class="dz-media-card style-4">
												<div class="dz-media">
                          <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2{{ movie.poster_path }}" alt="{{ movie.title }}">
												</div>
												<div class="dz-content">
													<div class="left-content">
														<h6 class="title">{{movie.title}}</h6>	
														<span >Release Date: {{movie.release_date}}</span>
													</div>
												</div>
										</div>
									</div>
                  {% endfor %}
								</div>
							</div>

							<div class="title-bar">
								<h6 class="title">Liked Movies</h6>
							</div>

							<div class="swiper spot-swiper1 mb-3">
								<div class="swiper-wrapper">
                  {% for movie in user.movies_liked.all %}
									<div class="swiper-slide">
										<div class="dz-media-card style-4">
												<div class="dz-media">
                          <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2{{ movie.poster_path }}" alt="{{ movie.title }}">
												</div>
												<div class="dz-content">
													<div class="left-content">
														<h6 class="title">{{movie.title}}</h6>	
														<span >Release Date: {{movie.release_date}}</span>
													</div>
												</div>
										</div>
									</div>
                  {% endfor %}
								</div>
							</div>

							<div class="title-bar">
								<h6 class="title">Disiked Movies</h6>
							</div>

							<div class="swiper spot-swiper1 mb-3">
								<div class="swiper-wrapper">
                  {% for movie in user.movies_disliked.all %}
									<div class="swiper-slide">
										<div class="dz-media-card style-4">
												<div class="dz-media">
                          <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2{{ movie.poster_path }}" alt="{{ movie.title }}">
												</div>
												<div class="dz-content">
													<div class="left-content">
														<h6 class="title">{{movie.title}}</h6>	
														<span >Release Date: {{movie.release_date}}</span>
													</div>
												</div>
										</div>
									</div>
                  {% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>								
	</div>
{% endblock %}